#!/bin/sh

sourcesPath=(
    NestedTime
    nestingDsInterpolator    
    nestedBlendDsPimpleSolver
    masterPimpleSolver
    nestedBlendDsBuoyBousLESPimpleSolver
    masterBuoyBousLESPimpleSolver
)

BoundaryConditionsPath=(
    FilteredNoiseInflowGenerator
    FilteredNoiseInflowGeneratorScalar
    LEMOSinflowGeneratorMod
    nestedBlendedTemperature
    nestedBlendedVelocity
)

functionObjectsPath=(
    CnC
    scalarVelocityProduct
    timeAbort
)

samplingPath=(
    sampledSurface/writers/foamFileSmall
    sampledSurface/writers/hdf5
)

solversPath=(
#     pisoScalarFoam
#     pisoScalarSourceFoam
#     pisoScalarSourceFoam221
    pisoScalarSourceFoam230
    nestedImpBlendDsPimpleFoam
    nestedImpBlendDsBuoyBousLESPimpleFoam
)

utilitiesPath=(
    cellVolumes
    gradU
    LESdelta
    patchDistance
    postAvg
    Q2D
    resLES
    scalarCovariance
    scalarFluxes
    SGSValues
    snGradU
    wallHeatFluxIncompressible
    yPlusMeanLES    
)

workingDir=$(pwd)

# compile the sources
echo "-------------------"
echo "compile the sources"
echo "-------------------"
cd src
locdir=$(pwd)
for i in "${sourcesPath[@]}"
do
    cd $i
    wmake
    cd $locdir    
done
cd $workingDir
echo ""

# compile the boundary conditions
echo "-------------------------------"
echo "compile the boundary conditions"
echo "-------------------------------"
cd BC
locDir=$(pwd)
for i in "${BoundaryConditionsPath[@]}"
do
    cd $i
    wmake
    cd $locDir    
done
cd $workingDir
echo ""

# compile the function objects
echo "----------------------------"
echo "compile the function objects"
echo "----------------------------"
cd FunctionObjects
locDir=$(pwd)
echo $locDir
for i in "${functionObjectsPath[@]}"
do 
    cd $i
    wmake
    cd $locDir 
done
cd $workingDir
echo ""


# compile the sampling libraries
echo "------------------------------"
echo "compile the sampling libraries"
echo "------------------------------"
cd sampling
locDir=$(pwd)
for i in "${samplingPath[@]}"
do 
    cd $i
    wmake
    cd $locDir
done
cd $workingDir
echo ""


# compile the solvers
echo "-------------------"
echo "compile the solvers"
echo "-------------------"
cd Solvers
locDir=$(pwd)
for i in "${solversPath[@]}"
do
    cd $i
    wmake
    cd $locDir
done
cd $workingDir
echo ""


# compile the utilities
echo "---------------------"
echo "compile the utilities"
echo "---------------------"
cd Utilities
locDir=$(pwd)
for i in "${utilitiesPath[@]}"
do
    cd $i
    wmake
    cd $locDir   
done
cd $workingDir
echo ""


